/*
                SC-504 Lenguajes de Base de Datos


                        Universidad Fidélistas.


                            III Avance


                            Integrantes:
                    Ortega Salas Diego Alexander.
                         Mata Tencio Fabián.
                    Nuñez Vargas Cristopher Enrique.
                     Jiménez Zambrana Jonathan.
                   Henry Calderon Yarling Darina.

                Prof. Profesor Jerson Morales Mendoza.


                            V Cuatrimestre
                        22 de Julio del 2024

*/

/*
    1. Creación del usuario y esquema,  linea 36 a la 53
    
    2. Creación de tablas, PKs, FKs e indices, linea 56 a la 226
    
    3. Inserción de datos dentro de las tablas, linea 229 a la #

*/

--1. Creación del usuario y esquema,  linea 36 a la 53
CREATE USER G6_SC504_VT_Proyecto IDENTIFIED BY 12345;
/
GRANT DBA TO G6_SC504_VT_Proyecto; 
/
GRANT CONNECT TO G6_SC504_VT_Proyecto;
/
GRANT CREATE SESSION TO G6_SC504_VT_Proyecto;
/
GRANT RESOURCE TO G6_SC504_VT_Proyecto;
/
GRANT CREATE VIEW TO G6_SC504_VT_Proyecto;
/
GRANT CREATE MATERIALIZED VIEW TO G6_SC504_VT_Proyecto;
/
GRANT CREATE TABLESPACE TO G6_SC504_VT_Proyecto;
/
GRANT ALTER DATABASE TO G6_SC504_VT_Proyecto;
/

--2. Creación de tablas, PKs, FKs e indices, linea 56 a la 226
CREATE TABLE G6_SC504_VT_Proyecto.FIDE_ROL_TB(
    ID_ROL NUMBER,
    DESCRIPCION VARCHAR2(50),
    NOMBRE_ROL VARCHAR2(50),
    FECHA_CREACION VARCHAR2(100),
    CREADO_POR VARCHAR2(40),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ACCION VARCHAR2(100),
    CONSTRAINT FIDE_ROL_TB_ID_ROL_PK PRIMARY KEY(ID_ROL)
                              USING INDEX(CREATE INDEX FIDE_ROL_TB_IDX ON FIDE_ROL_TB(ID_ROL))
);
/
CREATE TABLE G6_SC504_VT_Proyecto.FIDE_CALIFICACION_TB(
    ID_CALIFICACION NUMBER,
    ESTRELLAS NUMBER,
    FECHA_CREACION VARCHAR2(100),
    CREADO_POR VARCHAR2(40),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ACCION VARCHAR2(100),
    CONSTRAINT FIDE_CALIFICACION_TB_ID_CALIFICACION_PK PRIMARY KEY(ID_CALIFICACION)
                              USING INDEX(CREATE INDEX FIDE_CALIFICACION_TB_ID_CALIFICACION_IDX ON FIDE_CALIFICACION_TB(ID_CALIFICACION))
);

CREATE TABLE G6_SC504_VT_Proyecto.FIDE_ESTADO_TB(
    ID_ESTADO NUMBER,
    TIPO_ESTADO VARCHAR2(50),
    NOMBRE_ESTADO VARCHAR2(200),
    FECHA_CREACION VARCHAR2(100),
    CREADO_POR VARCHAR2(40),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ACCION VARCHAR2(100),
    CONSTRAINT FIDE_ESTADO_TB_ID_ESTADO_PK PRIMARY KEY(ID_ESTADO)
                              USING INDEX(CREATE INDEX FIDE_ESTADO_TB_ID_ESTADO_IDX ON FIDE_ESTADO_TB(ID_ESTADO))
);
/
CREATE TABLE G6_SC504_VT_Proyecto.FIDE_USUARIOS_TB(
    ID_USUARIO NUMBER,
    NOMBRE VARCHAR2(40),
    PRIMER_APELLIDO VARCHAR2(50),
    SEGUNDO_APELLIDO VARCHAR2(50),
    USERNAME VARCHAR2(30),
    CORREO_ELECTRONICO VARCHAR2(50),
    CONTRASENNA VARCHAR2(30),
    FOTO_PERFIL_URL VARCHAR2(3000),
    FECHA_CREACION VARCHAR2(100),
    CREADO_POR VARCHAR2(40),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ACCION VARCHAR2(100),
    ID_ROL NUMBER,
    CONSTRAINT FIDE_USUARIOS_TB_ID_USUARIO_PK PRIMARY KEY(ID_USUARIO)
                              USING INDEX(CREATE INDEX FIDE_USUARIOS_TB_ID_USUARIO_IDX ON FIDE_USUARIOS_TB(ID_USUARIO)),
    CONSTRAINT FIDE_USUARIOS_TB_ID_ROL_FK FOREIGN KEY(ID_ROL)
                              REFERENCES G6_SC504_VT_Proyecto.FIDE_ROL_TB(ID_ROL)
);
/
CREATE TABLE G6_SC504_VT_Proyecto.FIDE_PRESUPUESTO_TB(
    ID_PRESUPUESTO NUMBER,
    MONTO_TOTAL NUMBER(12,2),
    CREATE_AT DATE,
    FECHA_CREACION VARCHAR2(100),
    CREADO_POR VARCHAR2(40),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ACCION VARCHAR2(100),
    ID_USUARIO NUMBER,
    CONSTRAINT FIDE_PRESUPUESTO_TB_ID_PRESUPUESTO_PK PRIMARY KEY(ID_PRESUPUESTO)
                              USING INDEX(CREATE INDEX FIDE_PRESUPUESTO_TB_ID_PRESUPUESTO_IDX ON FIDE_PRESUPUESTO_TB(ID_PRESUPUESTO)),
    CONSTRAINT FIDE_PRESUPUESTO_TB_ID_USUARIO_FK FOREIGN KEY(ID_USUARIO)
                              REFERENCES G6_SC504_VT_Proyecto.FIDE_USUARIOS_TB(ID_USUARIO)
);
/
CREATE TABLE G6_SC504_VT_Proyecto.FIDE_PRESUPUESTO_DESGLOSE_TB(
    ID_PRESUPUESTO_DESGLOSE NUMBER,
    MONTO NUMBER(12,2),
    NOMBRE VARCHAR2(40),
    FECHA_CREACION VARCHAR2(100),
    CREADO_POR VARCHAR2(40),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ACCION VARCHAR2(100),
    ID_PRESUPUESTO NUMBER,
    CONSTRAINT FIDE_PRESUPUESTO_DESGLOSE_TB_ID_PRESUPUESTO_DESGLOSE_PK PRIMARY KEY(ID_PRESUPUESTO_DESGLOSE)
                              USING INDEX(CREATE INDEX FIDE_PRESUPUESTO_DESGLOSE_TB_ID_PRESUPUESTO_DESGLOSE_IDX ON FIDE_PRESUPUESTO_DESGLOSE_TB(ID_PRESUPUESTO_DESGLOSE)),
    CONSTRAINT FIDE_PRESUPUESTO_DESGLOSE_TB_ID_PRESUPUESTO_FK FOREIGN KEY(ID_PRESUPUESTO)
                              REFERENCES G6_SC504_VT_Proyecto.FIDE_PRESUPUESTO_TB(ID_PRESUPUESTO)
);
/
CREATE TABLE G6_SC504_VT_Proyecto.FIDE_CATEGORIA_TRANSACCION_TB(
    ID_TRANSACCION NUMBER,
    TIPO_TRANSACCION VARCHAR2(60),
    FECHA_CREACION VARCHAR2(100),
    CREADO_POR VARCHAR2(40),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ACCION VARCHAR2(100),
    ID_USUARIO NUMBER,
    CONSTRAINT FIDE_CATEGORIA_TRANSACCION_TB_ID_TRANSACCION_PK PRIMARY KEY(ID_TRANSACCION)
                              USING INDEX(CREATE INDEX FIDE_CATEGORIA_TRANSACCION_TB_ID_TRANSACCION_IDX ON FIDE_CATEGORIA_TRANSACCION_TB(ID_TRANSACCION)),
    CONSTRAINT FIDE_CATEGORIA_TRANSACCION_TB_ID_USUARIO_FK FOREIGN KEY(ID_USUARIO)
                              REFERENCES G6_SC504_VT_Proyecto.FIDE_USUARIOS_TB(ID_USUARIO)
);
/
CREATE TABLE G6_SC504_VT_Proyecto.FIDE_CATEGORIA_GASTOS_TB(
    ID_GASTO NUMBER,
    MONTO_GASTO NUMBER(12,2),
    DESCRIPCION_GASTO VARCHAR2(200),
    FECHA_GASTO DATE,
    FECHA_CREACION VARCHAR2(100),
    CREADO_POR VARCHAR2(40),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ACCION VARCHAR2(100),
    ID_USUARIO NUMBER,
    ID_TRANSACCION NUMBER,
    CONSTRAINT FIDE_CATEGORIA_GASTOS_TB_ID_GASTO_PK PRIMARY KEY(ID_GASTO)
                              USING INDEX(CREATE INDEX FIDE_CATEGORIA_GASTOS_TB_ID_GASTO_IDX ON FIDE_CATEGORIA_GASTOS_TB(ID_GASTO)),
    CONSTRAINT FIDE_CATEGORIA_GASTOS_TB_ID_USUARIO_FK FOREIGN KEY(ID_USUARIO)
                              REFERENCES G6_SC504_VT_Proyecto.FIDE_USUARIOS_TB(ID_USUARIO),
    CONSTRAINT FIDE_CATEGORIA_GASTOS_TB_ID_TRANSACCION_FK FOREIGN KEY(ID_TRANSACCION)
                              REFERENCES G6_SC504_VT_Proyecto.FIDE_CATEGORIA_TRANSACCION_TB(ID_TRANSACCION)
);
/
CREATE TABLE G6_SC504_VT_Proyecto.FIDE_RESENNAS_TB(
    ID_RESENNA NUMBER,
    DETALLE VARCHAR2(200),
    DESCRIPCION VARCHAR2(800),
    FECHA_CREACION VARCHAR2(100),
    CREADO_POR VARCHAR2(40),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ACCION VARCHAR2(100),
    ID_USUARIO NUMBER,
    ID_CALIFICACION NUMBER,
    CONSTRAINT FIDE_RESENNAS_TB_ID_RESENNA_PK PRIMARY KEY(ID_RESENNA)
                              USING INDEX(CREATE INDEX FIDE_RESENNAS_TB_ID_RESENNA_IDX ON FIDE_RESENNAS_TB(ID_RESENNA)),
    CONSTRAINT FIDE_RESENNAS_TB_ID_USUARIO_FK FOREIGN KEY(ID_USUARIO)
                              REFERENCES G6_SC504_VT_Proyecto.FIDE_USUARIOS_TB(ID_USUARIO),
    CONSTRAINT FIDE_RESENNAS_TB_ID_CALIFICACION_FK FOREIGN KEY(ID_CALIFICACION)
                              REFERENCES G6_SC504_VT_Proyecto.FIDE_CALIFICACION_TB(ID_CALIFICACION)
);
/
CREATE TABLE G6_SC504_VT_Proyecto.FIDE_INGRESOS_TB(
    ID_INGRESO NUMBER,
    FUENTE_INGRESO VARCHAR2(50),
    DESCRIPCION_INGRESO VARCHAR2(200),
    MONTO_INGRESO NUMBER(10,2),
    FECHA_INGRESO DATE,
    FECHA_CREACION VARCHAR2(100),
    CREADO_POR VARCHAR2(40),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ACCION VARCHAR2(100),
    ID_USUARIO NUMBER,
    ID_TRANSACCION NUMBER,
    CONSTRAINT FIDE_INGRESOS_TB_ID_INGRESO_PK PRIMARY KEY(ID_INGRESO)
                              USING INDEX(CREATE INDEX FIDE_INGRESOS_TB_ID_INGRESO_IDX ON FIDE_INGRESOS_TB(ID_INGRESO)),
    CONSTRAINT FIDE_INGRESOS_TB_ID_USUARIO_FK FOREIGN KEY(ID_USUARIO)
                              REFERENCES G6_SC504_VT_Proyecto.FIDE_USUARIOS_TB(ID_USUARIO),
    CONSTRAINT FIDE_INGRESOS_TB_ID_TRANSACCION_FK FOREIGN KEY(ID_TRANSACCION)
                              REFERENCES G6_SC504_VT_Proyecto.FIDE_CATEGORIA_TRANSACCION_TB(ID_TRANSACCION)
);
/
CREATE TABLE G6_SC504_VT_Proyecto.FIDE_OBJETIVOS_FINANCIEROS_TB(
    ID_OBJETIVO NUMBER,
    NOMBRE_OBJETIVO VARCHAR2(40),
    DESCRIPCION_OBJETIVO VARCHAR2(100),
    MONTO_OBJETIVO NUMBER(10,2),
    FECHA_TOPE DATE,
    FECHA_CREACION VARCHAR2(100),
    CREADO_POR VARCHAR2(40),
    MODIFICADO_POR VARCHAR2(100),
    FECHA_MODIFICACION DATE,
    ACCION VARCHAR2(100),
    ID_GASTOS NUMBER,
    ID_USUARIO NUMBER,
    ID_ESTADO NUMBER,
    ID_TRANSACCION NUMBER,
    ID_INGRESO NUMBER,
    ID_PRESUPUESTO NUMBER,
    CONSTRAINT FIDE_OBJETIVOS_FINANCIEROS_TB_ID_OBJETIVO_PK PRIMARY KEY(ID_OBJETIVO)
                              USING INDEX(CREATE INDEX FIDE_OBJETIVOS_FINANCIEROS_TB_ID_OBJETIVO_IDX ON FIDE_OBJETIVOS_FINANCIEROS_TB(ID_OBJETIVO)),
    CONSTRAINT FIDE_OBJETIVOS_FINANCIEROS_TB_ID_GASTOS_FK FOREIGN KEY(ID_GASTOS)
                              REFERENCES G6_SC504_VT_Proyecto.FIDE_CATEGORIA_GASTOS_TB(ID_GASTO),
    CONSTRAINT FIDE_OBJETIVOS_FINANCIEROS_TB_ID_TRANSACCION_FK FOREIGN KEY(ID_TRANSACCION)
                              REFERENCES G6_SC504_VT_Proyecto.FIDE_CATEGORIA_TRANSACCION_TB(ID_TRANSACCION),
    CONSTRAINT FIDE_OBJETIVOS_FINANCIEROS_TB_ID_USUARIO_FK FOREIGN KEY(ID_USUARIO)
                              REFERENCES G6_SC504_VT_Proyecto.FIDE_USUARIOS_TB(ID_USUARIO),
    CONSTRAINT FIDE_OBJETIVOS_FINANCIEROS_TB_ID_ESTADO_FK FOREIGN KEY(ID_ESTADO)
                              REFERENCES G6_SC504_VT_Proyecto.FIDE_ESTADO_TB(ID_ESTADO),
    CONSTRAINT FIDE_OBJETIVOS_FINANCIEROS_TB_ID_INGRESO_FK FOREIGN KEY(ID_INGRESO)
                              REFERENCES G6_SC504_VT_Proyecto.FIDE_INGRESOS_TB(ID_INGRESO),
    CONSTRAINT FIDE_OBJETIVOS_FINANCIEROS_TB_ID_PRESUPUESTO_FK FOREIGN KEY(ID_PRESUPUESTO)
                              REFERENCES G6_SC504_VT_Proyecto.FIDE_PRESUPUESTO_TB(ID_PRESUPUESTO)
);
--3. Inserción de datos dentro de las tablas, linea 229 a la #
